version: '3.8'

services:
  stock-terminal:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POLYGON_API_KEY=${POLYGON_API_KEY:-demo}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-demo}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-demo}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
